name: Data Preprocessing

on:
  # Trigger when there is a change or push to the main branch
  push:
    branches:
      - main
  workflow_dispatch:  # Trigger manually via GitHub Actions UI

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_andrewbj.py

    - name: Commit and push processed data
      uses: EndBug/add-and-commit@v9
      with:
        add: 'preprocessing/diabetes_processed.csv'
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Update pre-processed data'
      env:
        GH_TOKEN: ${{ secrets.SECRET_TOKEN }}
